### ISSUE TITLE
pip installation issues README.md

### ISSUE THREAD

**Issue by rubinglen** [brinnaebent/cgmquantify#12]
I'm installing on Ubuntu and pip throws an error on install due to a missing readme file.   Here is the error I am gettting:

Collecting cgmquantify
  Using cached cgmquantify-0.5.tar.gz (4.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ms784f7n/cgmquantify_3fb9c5805f8f448fb3aface6a99b80a1/setup.py", line 9, in <module>
          with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ms784f7n/cgmquantify_3fb9c5805f8f448fb3aface6a99b80a1/README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Doraemonwei** [comment]
You can use this __init___.py file to replace original __init__.py file
[new_init](https://github.com/Doraemonwei/cgmquantify/blob/master/cgmquantify/__init__.py)
